In [10]:
import numpy as np
import timeit

In [5]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

### NumPy
- It is designed for efficiency on large arrays of data
- stores data in a contiguous block of memory
- NumPy arrays use much less memory than built-in Python sequences

In [15]:
# NumPy-based algorithms are generally 10 to 100 times faster than pure Python and use less memory
%timeit my_arr2 = my_arr * 2

517 μs ± 20.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
%timeit my_list2 = [x * 2 for x in my_list]

11.9 ms ± 179 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### ndarray (N-dimensional array object)
- fast, flexible container for large datasets in Python

In [16]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [17]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [21]:
# all of the elements have been multiplied by 10
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [24]:
# corresponding values in each cell in the array have been added to each other
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

### An ndarray is a generic multidimensional container for homogeneous data
- all of the elements must be the same type
- `shape`: a tuple indicating the size of each dimension
- `dtype`: an object describing the data type of the array

In [25]:
data.shape

(2, 3)

In [26]:
data.dtype

dtype('float64')

### Creating ndarrays
- Using `array` function, we can create an arry easily
- This accepts any sequence-like object (including other arrays) and produces a new NumPy array

In [27]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [29]:
# Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
arr2.ndim

2

In [31]:
arr2.shape

(2, 4)

`numpy.array` tires to infer a good data type for the array that it creates

In [32]:
arr1.dtype

dtype('float64')

In [33]:
arr2.dtype

dtype('int64')

In [36]:
# There are a number of other functions for creating new arrays
np.zeros(10) # creates arrays of 0s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [39]:
# creates an array without initializing its values to any particular value
# Caution: do not assume that empty function will return an arry of all zeros (returns uninitialized memory)
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [41]:
# this is an array-valued version of the built-in Python range function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [42]:
# convert or cast an array from one data type to another
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [43]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

### Basic Indexing and Slicing

In [44]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[5]

np.int64(5)

In [46]:
arr[5:8]

array([5, 6, 7])

In [48]:
# if you assign a scalar value to a slice, the value is propagated to the entire selection
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [49]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [51]:
# the mutations are reflected in the original array
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [53]:
# "bare" slice [:] will assign to all values in an array
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [56]:
# in a two-dimensional array, the elements at each index are one-dimensional arrays (not scalars)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [57]:
arr2d[0][2]

np.int64(3)

In [58]:
# we can also use comma-separted list of indices to select individual elements
arr2d[0, 2]

np.int64(3)

In [60]:
# 2 * 2 * 3 array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
# 2 * 3 array
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[1, 0]

array([7, 8, 9])

In [67]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [69]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [70]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [73]:
lower_dim_slice = arr2d[1, :2]

In [74]:
lower_dim_slice.shape

(2,)

In [75]:
lower_dim_slice

array([4, 5])

In [77]:
# a colon by itself means to take the entire axis
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [78]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])